### ISSUE TITLE
Exception when using conditionals in the shader.

### ISSUE THREAD

**Issue by MaxOw** [tobbebex/GPipe-Core#12]
When using conditionals in the shader I get exception:

> implicit cast from "float" to "bool"

From what I could understand, it seems like [here][1] in the
implementation of `IfB` you're specifying return type to `Bool` instead of
inferring it from branches?

[1]: https://github.com/tobbebex/GPipe-Core/blob/ef66ea27ea6689a4c08c9d6ea11d9dbe8cdf70f9/GPipe-Core/src/Graphics/GPipe/Internal/Expr.hs#L591

**Comment by tobbebex** [comment]
Thanks for the bug report!
