### ISSUE TITLE
Several instances of application (GLFW)

### ISSUE THREAD

**Issue by NCrashed** [tobbebex/GPipe-Core#20]
The second window doesn't render until you close the first application.

![screenshot from 2016-01-06 17-28-22](https://cloud.githubusercontent.com/assets/2116167/12144758/f9af12ea-b49a-11e5-9759-78d8a9172187.png)

System: Fedora 23 x64
Graphic board: GeForce 840M (OpenGL 4.4.0)

**Comment by tobbebex** [comment]
I suspect you aren't swapoing the buffers on both contexts. Do you have some code to share?

**Comment by tobbebex** [comment]
Oh, you ment running a single context application twice? Then I suspect that you are starving the other instance with the first. Are the first one utilizing the cpu at 100%?

**Comment by NCrashed** [comment]
Code: https://github.com/Teaspot-Studio/gore-and-ash/blob/master/testapp/src/client/Graphics.hs#L85

> Oh, you ment running a single context application twice? Then I suspect that you are starving the other instance with the first. Are the first one utilizing the cpu at 100%?

I've just ran application twice in separate terminals to debug networking logic. CPU usage (server and two clients): 

![screenshot from 2016-01-06 19-10-00](https://cloud.githubusercontent.com/assets/2116167/12147277/23ad5440-b4a9-11e5-8ec0-b64826c71280.png)

**Comment by tobbebex** [comment]
Thanks for the code! Can't see anything in it that suggests an error in GPipe, so I'm quite certain the behaviour is dependent on GLFW. I think you should open an issue on plredmond/GPipe-GLFW instead.
