### ISSUE TITLE
Wrap read**Texture in Just for added safety

### ISSUE THREAD

**Issue by SwiftsNamesake** [tobbebex/GPipe-Core#29]
Title says it all I think.

**Comment by tobbebex** [comment]
This is a matter of taste, and GPipe follows the convention in Prelude (like for tail and !!): The API should make the simple use cases simple, and the complex use cases possible. In most cases, the inputs to readTextureXX is static and then wrapping in Maybe would make the signature more complex. Having both versions would also make it distracting for newcomers.

You can easily write your own total readTextures functions if you like by just using the textureXXSizes functions to validate the input yourself.

**Comment by SwiftsNamesake** [comment]
Fair enough. I just figured that the purpose of this library is to prevent as many errors as possible at compile time. By the way, do the Haddock entries for `readTexture2D` et. al. mention the fact that they are non-total functions?

**Comment by tobbebex** [comment]
I do mention what kind of errors you can expect in the [tutorial](http://tobbebex.blogspot.se/2015/10/gpu-programming-in-haskell-using-gpipe.html), but you are right that it's probably a good idea to add a note for each function that accepts an integer as input that it is partial and will error if the integer is out of bounds. 

If this were Idris I could encode the valid ranges in the type system. Returning a Maybe also has the disadvantage that you don't get an error message, and using an Either as return type is even more noisy...

**Comment by SwiftsNamesake** [comment]
I'd be fine with a note in the api docs. At least until we're graced with
dependent/constrained types (forgot the exact CS term)
tors 17 nov. 2016 kl. 21:46 skrev tobbebex <notifications@github.com>:
