### ISSUE TITLE
"discard" in fragment shader

### ISSUE THREAD

**Issue by RnMss** [tobbebex/GPipe-Core#31]
Is there a way to perform the "discard" operation in fragment shader?
I'd expect something like
```haskell
drawContextMaybeColor :: ContextColorFormat c 
        => (s -> ContextColorOption c)
        -> FragmentStream (Maybe (FragColor c))
        -> Shader os (ContextFormat c ds) s ()
```

**Comment by tobbebex** [comment]
Yes, there is:
http://hackage.haskell.org/package/GPipe-2.1.8/docs/Graphics-GPipe-FragmentStream.html#v:filterFragments



Den 17 mars 2017 08:56 skrev DreamApart <notifications@github.com>:

Is there a way to perform the "discard" operation in fragment shader?
e.g. something like ContextColorFormat c => (s -> ContextColorOption c) -> FragmentStream (Maybe (FragColor c)) -> Shader os (ContextFormat c ds) s ()
