### ISSUE TITLE
Question about the docstrings on ContextHandler which discuss threads

### ISSUE THREAD

**Issue by plredmond** [tobbebex/GPipe-Core#32]
The docstrings in [Internal/Context.hs#L59-L79](https://github.com/tobbebex/GPipe-Core/blob/38bd9d5f561ebdd08cefbd2562120592e1cd96f4/GPipe-Core/src/Graphics/GPipe/Internal/Context.hs#L59-L79) discuss calling the various `ContextHandler` typeclass functions "from the main thread" or "from the same thread as created the context", etc. I don't see fork anywhere in the codebase. Is that just from a previous version?

**Comment by tobbebex** [comment]
Finalizers for various opengl objects (buffers, textures, etc) are run by the haskell runtime from background threads and will call contextDoAsync, which then need to be threadsafe. This is the same as in previous version.

Other than that, you are right that GPipe aren't calling anything from other threads (but I'd like to keep that option open for future versions if we want to e.g. allow asynchronous GPU transfers).
