### ISSUE TITLE
[new-window-handling-interface] `windowSize` confusingly backed by `contextFrameBufferSize`

### ISSUE THREAD

**Issue by plredmond** [tobbebex/GPipe-Core#35]
GLFW supports both glfwGetWindowSize (screen coordinates) and glfwGetFramebufferSize (pixels) to support high resolution screens such as [Apple Retina](https://developer.apple.com/library/content/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Explained/Explained.html). I'm not sure exactly what's required to render correctly, but at least the names should match. :)

**Comment by tobbebex** [comment]
Ah, good point! Will update the name.
