### ISSUE TITLE
[new-window-handling-interface] GPipe-GLFW compatibility

### ISSUE THREAD

**Issue by plredmond** [tobbebex/GPipe-Core#36]
With a few small tweaks to GPipe
https://github.com/plredmond/GPipe-Core/tree/new-window-handler-interface
.. the new handler library works ...
https://github.com/plredmond/GPipe-GLFW/tree/new-window-handling-interface
.. and here is an example:
https://github.com/plredmond/GPipe-Test/tree/new-window-handling-interface

The `stack.yaml` files have been strung together to point at the right Github commits. If you just clone the last repo and `stack build` while on the branch, you should be good.

---

The new GPipe-GLFW is basically a three-day rewrite, because why not.
* Not tested with multithreaded applications, though it is designed to support them, ish.
* It requires that you run `mainloop` or regularly call `mainstep` in the mainthread to process RPCs of GLFW functions which /must/ be called on the mainthread.
* It naively calls `makeContextCurrent` whenever `contextDoAsync` occurs.

---

I'm doing a refactor to better support multithreaded/multicontext applications. The gist of the rewrite is that each context will live on its own thread permanently and calls to `contextDoAsync` will RPC to the appropriate thread. It's all through shared memory, so it shouldn't cause more trouble than constant pipeline drains would.

**Comment by plredmond** [comment]
Refactored a bit and set aside the idea of making threads & contexts 1:1. Let's see how far we can get calling `makeContextCurrent` when necessary.

**Comment by plredmond** [comment]
These branches are now up to date with the changes in https://github.com/plredmond/GPipe-GLFW/issues/21

**Comment by tobbebex** [comment]
All necessary changes are in master now. @plredmond, should we do a coordinated release?

**Comment by plredmond** [comment]
Sounds good! How do you want to do it?



One thing I wanted to do before release was update the quake3 port to see
if we have any speed improvements.

https://github.com/csabahruska/gpipe-quake3

If there is a lot of 'makeContextCurrent' I might change the threading
underneath to make them unnecessary.

This doesn't block release though. It's just fun :)

**Comment by tobbebex** [comment]
Sounds great! That is a good benchmark project.

Then I close this as done and submit a 2.2 to hackage. Feel free to do the same with Gpipe-GLFW.

**Comment by plredmond** [comment]
I'll upload tonight!

**Comment by plredmond** [comment]
http://hackage.haskell.org/package/GPipe-GLFW-1.4.0 !!

**Comment by plredmond** [comment]
We've got to get back on stackage now.

**Comment by tobbebex** [comment]
Yes! Will add us tonight unless you bet me to it ;)

**Comment by plredmond** [comment]
You beat me to it.
https://github.com/fpco/stackage/search?utf8=%E2%9C%93&q=GPipe&type=

**Comment by tobbebex** [comment]
No, thats from last year. Its still commented out...

**Comment by tobbebex** [comment]
But a pull request is in now...
