### ISSUE TITLE
[new-window-handling-interface] What does `contextDoAsync` with `Nothing` mean?

### ISSUE THREAD

**Issue by plredmond** [tobbebex/GPipe-Core#37]
```haskell
-- | Run an OpenGL IO action in this context, that doesn't return any value to the caller. This may be run after contextDelete or contextHandlerDelete has been called.
--   The thread calling this may not be the same creating the context (for finalizers it is most definetly not).
contextDoAsync :: ctx -> Maybe (ContextWindow ctx) -> IO () -> IO ()
```

If `Nothing` is passed in for the second argument, `Maybe (ContextWindow ctx)`, exactly where and how should the `IO ()` action be executed?

**Comment by tobbebex** [comment]
Nothing is used for a command that can be issued on any of the shared contexts of this context handler. If I remember corectly its nly used for finalizers of buffers and images (that doesnt know which contexts are still alive), but this may change...

**Comment by tobbebex** [comment]
Compare with finalizers for FBOs and VAOs, they do have a Just window, and if that window is already closed the io action must not be called at all (since VAOs and FBOs unlike other objects aren't shared between shared contexts)
