### ISSUE TITLE
Have any plan to move to GHC8.0.2?

### ISSUE THREAD

**Issue by TsumiNa** [tobbebex/GPipe-Core#38]
I use stack LTS to manage my projects. Now almost all these active libs has been moved to GHC8.0.2. So I want to know if possible to move GPipe2 to 8.0.2.

**Comment by plredmond** [comment]
Tobias usually updates to the latest nightly on his dev builds, so the next GPipe release will probably be on the latest lts or so.

**Comment by tobbebex** [comment]
Done in 6428498

**Comment by tobbebex** [comment]
Remember to use latest stack (1.4.0) since they just added support for custom-setup that gl-0.8.0 uses.

**Comment by TsumiNa** [comment]
Thanks!!
