### ISSUE TITLE
Stencil Textures do not work

### ISSUE THREAD

**Issue by raymoo** [tobbebex/GPipe-Core#45]
I tried to create and use a stencil texture and I cannot use it properly. Here are the things I tried:
 - Creating a `Texture2D os (Format Stencil)` with 8 bit and 16 bit formats - no visible errors on creation
 - Clearing the stencil texture (with clearImageStencil) - results in GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
 - Using the stencil buffer for stencil tests (using workarounds to clear the stencil buffer) - the stencil buffer is ignored and is not tested before drawing. I also tried just having one draw with `Never` as the stencil test, and it appeared to pass each time.

I will try to put together a demo project after finals week.

**Comment by tobbebex** [comment]
Im seing the same thing actually. Seems like my GL-driver doesnt like stencil FBO attachments, doing the same with depth images works fine, and the code is very similar. Will investigate this further...

**Comment by SwiftsNamesake** [comment]
Any news?

**Comment by tobbebex** [comment]
Yes, sorry, vacation got in the way... 

Well, seems that this is not required to be supported by OpenGl 3.3 implementations, and NVidia seems to not do it. 

From “Required Framebuffer Formats” in section 4.4.4 of OpenGl 3.3 specs:

> Implementations must support framebuffer objects with up to MAX_COLOR_-
ATTACHMENTS color attachments, a depth attachment, and a stencil attachment.
Each color attachment may be in any of the required color formats for textures
and renderbuffers described in sections 3.8.3 and 4.4.2. **The depth attachment may
be in any of the required depth or combined depth+stencil formats described in
those sections, and the stencil attachment may be in any of the required combined
depth+stencil formats.**

So, as opposed to stand-alone depth buffers, stand-alone stencil buffers are not (required to be) allowed to be attached to an FBO.

Try using a Texture2D os (Format DepthStencil) instead (albeit with waste of space).

**Comment by tobbebex** [comment]
I'll remove those formats as TextureFormats altogether

**Comment by raymoo** [comment]
It's been some time but I remember having the same problems when using a combined depth stencil buffer as well. Does it work for you?
