### ISSUE TITLE
Runtime error in simple fragment program.

### ISSUE THREAD

**Issue by MaxOw** [tobbebex/GPipe-Core#5]
I got a runtime error when testing GPipe. I took the sample
program from the first part of the tutorial and tried to modify it to
map all fragments to red.

```haskell
drawContextColor
    (const (ContextColorOption NoBlending (V3 True True True)))
    (V3 1 0 0 <$ fragmentStream)
```

The error was:

```
Too few attributes generated in toPrimitiveStream
thread blocked indefinitely in an MVar operation
```

Surprisingly, this works: 

```haskell
drawContextColor
    (const (ContextColorOption NoBlending (V3 True True True)))
    ((\(V3 a _ _) -> V3 a 0 0) <$> fragmentStream)
```

So that's weird.

**Comment by tobbebex** [comment]
Thanks for the bug report!

Turned out to be a severe bug, but with an easy fix.
