### ISSUE TITLE
Is there a good way to load fonts in GPipe?

### ISSUE THREAD

**Issue by DevJac** [tobbebex/GPipe-Core#54]
I'm currently using FreeType to load some fonts into GPipe textures. I was wondering if there is a better way?

It not, I'll try to make a library once I'm sure I know what I'm doing.

**Comment by tobbebex** [comment]
No, GPipe has no font loading built in. The abstraction level of GPipe is the same as of OpenGl 3.3, which doesnt have a concept of fonts either.

But a font-library built on top of GPipe is a good idea! Good luck!
