### ISSUE TITLE
Viewport update on window resize

### ISSUE THREAD

**Issue by Kludgy** [tobbebex/GPipe-Core#59]
Is there a way to update the viewport without recompiling fragment shaders? (Should there be?)

**Comment by tobbebex** [comment]
Yes, the Viewport is provided to the rasterize function as a function over the Shader monad environment s. So you can create a CompiledShader that takes the Viewport as argument, eg (ViewPort, SomeOtherDataYouNeedPerFrame) -> Render os ().

Hope that helps!

**Comment by Kludgy** [comment]
Yes that was the missing piece for me, thank you!
