### ISSUE TITLE
2018 - base > 4.11 version changes / Gpipe Semigroup / GPipe-GLFW bitsToHints

### ISSUE THREAD

**Issue by ImreMD** [tobbebex/GPipe-Core#63]
Just to inform that I manage to run GPipe with new Base with Stack, steps:
- use allow-newer in config.yaml
- instanciate PrimitiveArray & PrimitiveStream & Fragment Stream in ../GPipe/Internal from Semigroup: basically define `(<>) as mappend` 
- correct function `bitsToHints (Just ((red, green, blue, alpha, sRGB), depth, stencil)) ` :
   `, GLFW.WindowHint'RedBits red` tp ` GLFW.WindowHint'RedBits (Just red)` same for others fields

**Comment by tobbebex** [comment]
Library versions bumped (so no need for allow-newer), and Semigroup is derived for those types. bitsToHints is in GPipe-GLFW
