### ISSUE TITLE
hackage out of sync

### ISSUE THREAD

**Issue by nek0** [tobbebex/GPipe-Core#64]
Hi,

I was wondering if there is a special reason that the version of GPipe on hackage is significantly older than the last commit on the master branch here.

**Comment by tobbebex** [comment]
No special reason. Just haven’t been done yet!

**Comment by nek0** [comment]
Can you upddate the hackage repo then? Thank you.

**Comment by tobbebex** [comment]
Sure, but wont have time until next weekend though...

**Comment by nek0** [comment]
That's ok. Thanks none the less.

**Comment by tobbebex** [comment]
https://hackage.haskell.org/package/GPipe-2.2.4
