### ISSUE TITLE
GPipe works only in GHCi

### ISSUE THREAD

**Issue by DoctorRyner** [tobbebex/GPipe-Core#69]
This code:
http://tobbebex.blogspot.com/2015/09/gpu-programming-in-haskell-using-gpipe.html

Works fine from GHCi:
<img width="732" alt="Screenshot 2019-09-20 at 12 21 08 PM" src="https://user-images.githubusercontent.com/24430919/65315669-2fd1b180-dba1-11e9-9c29-98693b313bc9.png">

But when I compile it with GHC it gives me this:
<img width="732" alt="Screenshot 2019-09-20 at 12 20 19 PM" src="https://user-images.githubusercontent.com/24430919/65315702-3d873700-dba1-11e9-87e8-536532c3600b.png">

It's the latest resolver (lts-14.6) and basic stack project

**Comment by DoctorRyner** [comment]
It work when I change this from RGB8 to RBG16:
<img width="410" alt="Screenshot 2019-09-20 at 1 27 22 PM" src="https://user-images.githubusercontent.com/24430919/65320565-d3738f80-dbaa-11e9-93b4-16473cae6fc3.png">

But it doesn't make sense at all

**Comment by tobbebex** [comment]
Seems that you cannot create a RGB8 window on your system (it looks like it is creating an RGB16 without telling when you ask for it, thus the skewed result). I have no idea why it is allowed through GHCi though.

So this is GPU or driver specific, and unfortunately nothing that can be done on GPipe side.

Your mitigation is to use RGB16 instead.
